# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Client CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: frontend/package-lock.json
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install SSH Client
      working-directory: frontend
      run: sudo apt-get install openssh-client -y
    - name: Deploy using SSH
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd cafe-pos
          git pull origin main
          git status
          cd frontend
          npm ci
          npm run build
          rm -r /var/www/cafe-pos/*
          mv ./dist/* /var/www/cafe-pos
